spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 12345678

  thymeleaf:
    cache: false
  spring:
    mvc:
      hiddenmethod:
        filter:
         enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/project/*Mapper.xml
  type-aliases-package: com.lee.project.entity
logging:
  level:
    com.lee.project.dao: trace


